/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Venta;
import clasesmetodos.Ropa_metodos;
import clasesmetodos.Venta_metodos;
import java.awt.Font;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodosvarios.Fecha;
import metodosvarios.Varios;

/**
 *
 * @author
 */
public class Aparatado_ropa extends javax.swing.JInternalFrame {
    
DefaultTableModel modeloTabla;
DefaultListModel lista= new DefaultListModel();
Recibo recibo = new Recibo();
Recibos recibos= new Recibos();
Fecha fn= new Fecha();
Venta vn=new Venta();
Venta_metodos vm= new Venta_metodos();

Cambio_apartado2 cambio=new Cambio_apartado2();

Varios va= new Varios();

Cliente_buscar cliebus= new Cliente_buscar();
Ropa_metodos rm= new Ropa_metodos();
Validaciones val=new Validaciones();
public static String nombrevendededor=null;
    




    /**
     * Creates new form Aparatado_ropa
     */
    public Aparatado_ropa() {
        initComponents();
          this.setClosable(true);
        this.setMaximizable(true);
        String encabezado[]={"CLAVE","CANTIDAD","DESCRIPCION","PRECIO","TOTAL"}; String datos[][]={};
        modeloTabla=new DefaultTableModel(datos,encabezado); 
       
        
        
        
        tabla_ventas.setModel(modeloTabla);
        scrolltventas.setBackground(java.awt.Color.red);
        Atxtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        tabla_ventas.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        tabla_ventas.getTableHeader().setOpaque(false);
        tabla_ventas.getTableHeader().setBackground(java.awt.Color.WHITE);
        tabla_ventas.getTableHeader().setForeground(java.awt.Color.BLUE);
        tabla_ventas.setRowHeight(25);
      vcambio.setVisible(true);
      lista= new DefaultListModel();
    
      lid_venta.setVisible(false);
      lid_usuario.setVisible(false);
      lborrarrow.setVisible(true);
      txtfechainicio.setText(fn.fechaactual());
      Atxtcodigo.setEditable(true);
      txtfechafi.setEditable(false);
     
      Atxtcodigo.setEditable(false);
      txtnomclientea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lcodicolor = new javax.swing.JLabel();
        leliminarow = new javax.swing.JLabel();
        vcambio = new javax.swing.JPanel();
        lborrarrow = new javax.swing.JLabel();
        lcam = new javax.swing.JLabel();
        ldinerorecibido = new javax.swing.JLabel();
        lid_usuario = new javax.swing.JLabel();
        lid_venta = new javax.swing.JLabel();
        ventanatabla = new javax.swing.JPanel();
        scrolltventas = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfechafi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        larticulos = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        Atxtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Alpago = new javax.swing.JLabel();
        lv_idus = new javax.swing.JLabel();
        txtnomclientea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lid_cliente = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lcodicolor.setText("0");

        leliminarow.setText("-1");

        vcambio.setBackground(new java.awt.Color(255, 255, 255));

        lborrarrow.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lborrarrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lborrarrow.setText("0");

        javax.swing.GroupLayout vcambioLayout = new javax.swing.GroupLayout(vcambio);
        vcambio.setLayout(vcambioLayout);
        vcambioLayout.setHorizontalGroup(
            vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vcambioLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lborrarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        vcambioLayout.setVerticalGroup(
            vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vcambioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lborrarrow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lid_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lid_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lid_usuario.setText("1");

        lid_venta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lid_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lid_venta.setText("123");

        ventanatabla.setBackground(new java.awt.Color(255, 255, 255));

        scrolltventas.setBackground(new java.awt.Color(255, 255, 255));
        scrolltventas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        scrolltventas.setOpaque(false);

        tabla_ventas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_ventas.setFocusable(false);
        tabla_ventas.setGridColor(new java.awt.Color(51, 255, 51));
        tabla_ventas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla_ventas.setOpaque(false);
        tabla_ventas.setRowHeight(100);
        tabla_ventas.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabla_ventas.setShowVerticalLines(false);
        tabla_ventas.getTableHeader().setReorderingAllowed(false);
        scrolltventas.setViewportView(tabla_ventas);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FECHA DE FIN:");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        txtfechainicio.setFont(new java.awt.Font("Freestyle Script", 1, 32)); // NOI18N
        txtfechainicio.setForeground(new java.awt.Color(0, 51, 51));
        txtfechainicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechainicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FECHA DE INICIO:");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        txtfechafi.setFont(new java.awt.Font("Freestyle Script", 1, 32)); // NOI18N
        txtfechafi.setForeground(new java.awt.Color(0, 51, 51));
        txtfechafi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechafi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtfechafi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechafiActionPerformed(evt);
            }
        });
        txtfechafi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfechafiKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CANTIDAD DE ARTICULOS");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        larticulos.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        larticulos.setForeground(new java.awt.Color(0, 255, 0));
        larticulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        larticulos.setText("0");
        larticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                larticulosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanatablaLayout = new javax.swing.GroupLayout(ventanatabla);
        ventanatabla.setLayout(ventanatablaLayout);
        ventanatablaLayout.setHorizontalGroup(
            ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanatablaLayout.createSequentialGroup()
                .addGroup(ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrolltventas, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 294, Short.MAX_VALUE))
            .addGroup(ventanatablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanatablaLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfechafi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(larticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanatablaLayout.setVerticalGroup(
            ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanatablaLayout.createSequentialGroup()
                .addGroup(ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechafi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolltventas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(larticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelcodigo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcodigo.setText("CODIGO DE ROPA");
        labelcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcodigoMouseClicked(evt);
            }
        });

        Atxtcodigo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Atxtcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Atxtcodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));
        Atxtcodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Atxtcodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                AtxtcodigoCaretUpdate(evt);
            }
        });
        Atxtcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtxtcodigoMouseClicked(evt);
            }
        });
        Atxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtxtcodigoActionPerformed(evt);
            }
        });
        Atxtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AtxtcodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AtxtcodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AtxtcodigoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL DE APARTADO");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        Alpago.setFont(new java.awt.Font("Arial Narrow", 1, 45)); // NOI18N
        Alpago.setForeground(new java.awt.Color(51, 204, 0));
        Alpago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alpago.setText("0");

        lv_idus.setText("1555555555555555555");

        txtnomclientea.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtnomclientea.setForeground(new java.awt.Color(0, 51, 51));
        txtnomclientea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnomclientea.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 153)));
        txtnomclientea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomclienteaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("NOMBRE DEL CLIENTE");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(vcambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lcam, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(leliminarow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lcodicolor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lv_idus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(labelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(331, 331, 331)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txtnomclientea, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ventanatabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Atxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202)
                                .addComponent(Alpago, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(535, 535, 535)))))
                .addGap(0, 181, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1419, Short.MAX_VALUE)
                    .addComponent(ldinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Atxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnomclientea, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Alpago, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ventanatabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(leliminarow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcodicolor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lv_idus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(vcambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(lcam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(641, Short.MAX_VALUE)
                    .addComponent(ldinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        lid_cliente.setForeground(new java.awt.Color(0, 102, 0));
        lid_cliente.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(lid_cliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lid_cliente)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void AtxtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AtxtcodigoKeyTyped

    }//GEN-LAST:event_AtxtcodigoKeyTyped

    private void AtxtcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AtxtcodigoKeyReleased

        String codiropa=Atxtcodigo.getText();
        char c = evt.getKeyChar();
        int tamt_bla= modeloTabla.getRowCount();
        int clavetecla=evt.getExtendedKeyCode();
        String codiropabd=rm.ropaTDA(codiropa).getClave();

        ///////

        System.out.println("tecla = "+clavetecla);
        va.borracaja(Atxtcodigo, evt);

        if(Atxtcodigo.getText().isEmpty()){
            System.out.println("no hay en dinero recibido");
        }
       

        if(tamt_bla>=1){

            if(clavetecla==17){
                String vid_us=lv_idus.getText();
                cambio.setVisible(true);
                extraerdatostabla();
                int tana= modeloTabla.getRowCount();
                cambio.tamañodedatos1.setText(Integer.toString(tana));
                cambio.lid_usuarioc1.setText(lid_usuario.getText());
                cambio. ltotale1.setText(Alpago.getText());
                
                
         
                cambio.afecha="FECHA:"+" IN:"+ txtfechainicio.getText()+" FIN:"+txtfechafi.getText();
                cambio.avendedor=nombrevendededor;
                cambio.acliente=txtnomclientea.getText();
                
                Cambio_apartado2.id_client=lid_cliente.getText();
                Cambio_apartado2.afechainicio=txtfechainicio.getText();
                Cambio_apartado2. afechafin=txtfechafi.getText();
                cambio.lid_apartadoAP.setText("0");
                
                
              //  Cambio_apartado.nomcliente=txtnomclientea.getText();
               

            }

            /*
            String total_pago= lpago.getText();
            guardarventa();
            cambio.setVisible(true);
            cambio.ltotale.setText(total_pago);
            limpiartabla(tamt_bla);
            int id_i=Integer.parseInt (lid_venta.getText());
            String id_iv = Integer.toString((id_i + 1));

            lid_venta.setText(id_iv);

            //recibo.imprimirrecibo();
            */

        }
    }//GEN-LAST:event_AtxtcodigoKeyReleased

    private void AtxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtxtcodigoActionPerformed

        ventasaction();
    }//GEN-LAST:event_AtxtcodigoActionPerformed

    private void AtxtcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtxtcodigoMouseClicked
if(Atxtcodigo.isEditable()==false){
    JOptionPane.showMessageDialog(null,"ELIJA UN CLIENTE DANDO CLIC EN "+"(NOMBRE CLIENTE)");
}
    }//GEN-LAST:event_AtxtcodigoMouseClicked

    private void AtxtcodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_AtxtcodigoCaretUpdate

    }//GEN-LAST:event_AtxtcodigoCaretUpdate

    private void labelcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcodigoMouseClicked
        int lcl= Integer.parseInt(lcodicolor.getText());

        if(lcl==0){
            lcodicolor.setText("1");
            Atxtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        }
        else{
            lcodicolor.setText("0");
            Atxtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        }
        
        if(Atxtcodigo.isEditable()==false){
    JOptionPane.showMessageDialog(null,"ELIJA UN CLIENTE DANDO CLIC EN "+"(NOMBRE CLIENTE)");
}
    }//GEN-LAST:event_labelcodigoMouseClicked

    private void larticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_larticulosMouseClicked
        lista.clear();
    }//GEN-LAST:event_larticulosMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int tamañolabel=modeloTabla.getRowCount();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        cliebus.setVisible(true);
          cliebus.v_consulta=10;
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtfechafiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechafiKeyReleased
         int dia1=0;
         int mes1=0;
         int año1=0;
         int dia2=0;
         int mes2=0;
         int año2=0;
         
         
         /*
        if(val.vfecha(txtfechafi.getText())){
            String fc1=txtfechainicio.getText();
            String fc2=txtfechafi.getText();
          dia1=fn.edia(fc1);
           mes1=fn.emes( fc1);
          año1=fn.eaño( fc1);
          dia2=fn.edia(fc2);
         mes2=fn.emes(fc2);
          año2=fn.eaño(fc2);
          
          if(año1==año2 && mes2>mes1 && dia2>=dia1){
              
              Atxtcodigo.setEditable(true);
              
              
          }
          else{
               Atxtcodigo.setEditable(false);
                JOptionPane.showInternalMessageDialog(null,"LA FECHA TIENE QUE SER MAYOR A LA INICIAL");
          }
       
     }else{
        // JOptionPane.showInternalMessageDialog(null,);
     }*/
    }//GEN-LAST:event_txtfechafiKeyReleased

    private void txtfechafiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechafiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechafiActionPerformed

    private void txtnomclienteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomclienteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomclienteaActionPerformed

    private void AtxtcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AtxtcodigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtxtcodigoKeyPressed
public void limpiartabla(){
    int modlta= modeloTabla.getRowCount()-1;
    for (int o = modlta; o>-1; o--) {
        modeloTabla.removeRow(o);
    }
  } 





public void limpiarapatado(){
     limpiartabla();
     txtnomclientea.setText(null);
     txtfechafi.setEditable(false);
     Alpago.setText("0");
    // txtfechafi.setText(null);
     larticulos.setText("0");
     txtnomclientea.setText(null);
     lid_cliente.setText("0");
     Atxtcodigo.setEditable(false);
     Atxtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
}
    
   
   
   
    //////////////7777
      
    public void mostrarcliente(){
        cliebus.setVisible(true);
    }
    
   public void extraerdatostabla(){
        // DefaultTableModel modeloTabla = new DefaultTableModel();
        //tablaD.setModel(modeloTabla);
       int textraer = modeloTabla.getRowCount();
       
  
      
        
          for (int qr =0; qr< textraer; qr++) {
              System.out.println("Q= "+ qr);
            String tclave=tabla_ventas.getModel().getValueAt(qr, 0).toString();
            int tcantidad = Integer.parseInt(tabla_ventas.getModel().getValueAt(qr, 1).toString());
            String tdescripcion=tabla_ventas.getModel().getValueAt(qr, 2).toString();
            double tprecio = Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 3).toString());
            double totale= Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 4).toString());
            cambio.tablacambio1.setValueAt(tclave, qr, 0);
            cambio.tablacambio1.setValueAt(tcantidad, qr, 1);
            cambio.tablacambio1.setValueAt(tdescripcion, qr, 2);
            cambio.tablacambio1.setValueAt(tprecio, qr, 3);
            cambio.tablacambio1.setValueAt(totale, qr, 4);
            
         
        
    }
          
   }
      
      
            
      
      
      
      
      
      
      
    /////////777
    
    
    
   public void ventasaction(){
       int tam = tabla_ventas.getRowCount();
      
         String tipoa = Atxtcodigo.getText();
         String clave=rm.ropaTDA(tipoa).getClave();
        double precio = rm.ropaTDA(tipoa).getPrecio();
      String descripcion=rm.ropaTDA(tipoa).getTipo_producto()+" "+rm.ropaTDA(tipoa).getMarca()+" "+" "+rm.ropaTDA(tipoa).getTalla();
        
         int tcolor=Integer.parseInt(lcodicolor.getText());
        if(tipoa.equals(clave)){
           ventas(tam,precio,tipoa,tcolor,descripcion);  
        }
    
       Atxtcodigo.setText(null);
   } 
    
    
    public void m1(){
       int tamañovector=modeloTabla.getDataVector().size();
          if(tamañovector>0){
              double tf=0;
              int lart=0;
              for (int i =0; i < tamañovector; i++) {
           
                  double tprec=Double.parseDouble(tabla_ventas.getModel().getValueAt(i,4).toString());
                  int lrt=Integer.parseInt(tabla_ventas.getModel().getValueAt(i,1).toString());
                  
                tf=tf+tprec;
                lart=lart+lrt;
               
                  Alpago.setText(Double.toString(tf));
                  larticulos.setText(Integer.toString(lart));
}}
  }  
   
  
      
    public void ventas(int t,double precio,String tipoa,int tcolor,String descripcion){
       int opcion=0;

        int cantidad = 1;
        
        double total = precio * cantidad;
        
        Object registro[] = new Object[]{tipoa,cantidad,descripcion, precio, total};
        
         if(t==0){
           if(tcolor==0){
              opcion=1;
           }  
           if(tcolor==1){
              opcion=0;
           }  
        }
         
        if (t >= 1) {
       if(tcolor==0){
              opcion=2;
               System.out.println("condicio >1 para el case 2 = "+tcolor);
           }  
           if(tcolor==1){
              opcion=3;
               System.out.println("condicio >1 para el case 3 = "+tcolor);
           }  
        }
         
        switch(opcion){
            case 0:
                System.out.println("nada");  
            break;
                  
            case 1: 
            modeloTabla.addRow(registro);
           Alpago.setText(Double.toString(precio));
            larticulos.setText(Integer.toString(1));
             break;  
             
             
            case 2:
             
               if (vender(t, tipoa,1) == false) {
                modeloTabla.addRow(registro);
             
            }
         rellenatabla(t);
              
             break;
            case 3:
        
            int cvtam= cance_venta(t,tipoa,1);
            rellenatabla(t);
           int rowdelete=Integer.parseInt( leliminarow.getText());
            if(rowdelete>-1){
                System.out.println("HOLA"); 
                modeloTabla.removeRow(rowdelete);
                leliminarow.setText(Integer.toString(-1));
            }
            
                break;
            default:
                System.out.println("nada");
                break;
        }
    }
    
    public void rellenatabla(int t){
          for (int m = 0; m < t; m++) {
                
              int cant = Integer.parseInt(tabla_ventas.getModel().getValueAt(m, 1).toString());
            double prec = Double.parseDouble(tabla_ventas.getModel().getValueAt(m, 3).toString());
            double totale=cant*prec;
          
            tabla_ventas.setValueAt(totale,m, 4);
       
  //cancelarventa(t);
            m1();
        }
    }

    
    public boolean vender(int tam,String tipoa,int tcan ){
       boolean tt=false;
       int i=0;
             while (i<tam) { 
                   String cc = tabla_ventas.getModel().getValueAt(i,0).toString();
               if(cc.equals(tipoa)){
                    int can= Integer.parseInt(tabla_ventas.getModel().getValueAt(i,1).toString());
                       int ttcant = tcan;
                    
                        tabla_ventas.setValueAt((can + ttcant),i,1);
                        tt=true;
               }
               i++;
             }
                   return tt;
             }
    
    public int cance_venta(int tam,String tipoa,int tcan){
        int cv= -1;
       int ñ=0;
        
             while (ñ<tam) { 
       String cc = tabla_ventas.getModel().getValueAt(ñ,0).toString();
                
               if(cc.equals(tipoa)){
            
                    int canttt= Integer.parseInt(tabla_ventas.getModel().getValueAt(ñ,1).toString());
                      int ttcant = tcan;
                     int cantireal= (canttt - ttcant);
                    if(cantireal==0){
                        leliminarow.setText(Integer.toString(ñ));
                       cv=0;
                         
                    }
                    
                     tabla_ventas.setValueAt(cantireal,ñ,1);}
               ñ++;}
             return cv;}
    
     public void mostrardatos(String t) {
          lista= new DefaultListModel();
        
        lista.insertElementAt("CLAVE"+" TIPO"+" MARCA"+"DESCRIPCION"+"TALLA"+"PRECIO", 0);
   
        int numReg = rm.Ropatotal(t).size();
      

        for (int i = 0; i < numReg; i++) {
            
          String cla_r =  rm.Ropatotal(t).get(i).getClave();
          String tipo_r =  rm.Ropatotal(t).get(i).getTipo_producto();
          String marca_r =  rm.Ropatotal(t).get(i).getMarca();
          String desc_r =  rm.Ropatotal(t).get(i).getDescripcion();
          String talla_r =  rm.Ropatotal(t).get(i).getTalla();
          double precio_r =  rm.Ropatotal(t).get(i).getPrecio();
          
          lista.addElement(cla_r+" "+ tipo_r+" "+marca_r+" "+desc_r+" "+talla_r+" "+precio_r);
        }
    }

     public void guardarventa(){
         vn.setId_venta(lid_venta.getText());
         vn.setId_usuario(Integer.parseInt(lid_usuario.getText()));
         vn.setFecha(fn.fechaactual());
         vn.setHora(fn.hora_completa());
         vn.setTotal_venta(Alpago.getText());
         vm.guardar_venta(vn);
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Alpago;
    public javax.swing.JTextField Atxtcodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelcodigo;
    public javax.swing.JLabel larticulos;
    public javax.swing.JLabel lborrarrow;
    private javax.swing.JLabel lcam;
    private javax.swing.JLabel lcodicolor;
    private javax.swing.JLabel ldinerorecibido;
    private javax.swing.JLabel leliminarow;
    public javax.swing.JLabel lid_cliente;
    public javax.swing.JLabel lid_usuario;
    private javax.swing.JLabel lid_venta;
    public javax.swing.JLabel lv_idus;
    private javax.swing.JScrollPane scrolltventas;
    public javax.swing.JTable tabla_ventas;
    public javax.swing.JTextField txtfechafi;
    public javax.swing.JTextField txtfechainicio;
    public javax.swing.JTextField txtnomclientea;
    public javax.swing.JPanel vcambio;
    private javax.swing.JPanel ventanatabla;
    // End of variables declaration//GEN-END:variables
}
