/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Venta;
import clasesmetodos.Venta_metodos;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import metodosvarios.Fecha;

/**
 *
 * @author 
 */
public class Cambio extends javax.swing.JFrame {
    Validaciones1 val= new Validaciones1();
Recibos recibo2= new Recibos();
DefaultTableModel modeloTablaCambio;
Venta vn=new Venta();
Fecha fn= new Fecha();
Venta_metodos vm= new Venta_metodos();
public static String nombreus=null;
    /**
     * Creates new form El_cambio
     */
    public Cambio() {
        initComponents();
          this.setLocationRelativeTo(null);
         this.setAlwaysOnTop(true);
        ldarcambio.setVisible(false);
       lcambio.setVisible(false);
        String encabezado[]={"CLAVE","CANTIDAD"+"DESCRIPCION","PRECIO UNITARIO","SUBTOTAL"}; String datos[][]={};
         modeloTablaCambio=new DefaultTableModel(datos,encabezado);
         ltotale.setVisible(false);
         paneltabla.setVisible(false);
               this.setAlwaysOnTop(true);
         
         lclave_venta.setVisible(false);
         lc_claveventa.setVisible(false);
         lid_usuarioc.setVisible(false);
         tamañodedatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdinerorecibido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lcambio = new javax.swing.JLabel();
        ldarcambio = new javax.swing.JLabel();
        ltotale = new javax.swing.JLabel();
        tamañodedatos = new javax.swing.JLabel();
        lid_usuarioc = new javax.swing.JLabel();
        lclave_venta = new javax.swing.JLabel();
        lc_claveventa = new javax.swing.JLabel();
        paneltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacambio = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtdinerorecibido.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        txtdinerorecibido.setForeground(new java.awt.Color(51, 0, 102));
        txtdinerorecibido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdinerorecibido.setToolTipText("");
        txtdinerorecibido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtdinerorecibido.setCaretColor(new java.awt.Color(204, 0, 0));
        txtdinerorecibido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtdinerorecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdinerorecibidoActionPerformed(evt);
            }
        });
        txtdinerorecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdinerorecibidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdinerorecibidoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DINERO RECIBIDO");

        lcambio.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        lcambio.setForeground(new java.awt.Color(0, 204, 0));
        lcambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ldarcambio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ldarcambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldarcambio.setText("CAMBIO:");

        ltotale.setForeground(new java.awt.Color(255, 255, 255));
        ltotale.setText("0");

        tamañodedatos.setText("0");

        lid_usuarioc.setText("jLabel2");

        lclave_venta.setText("jLabel2");

        lc_claveventa.setText("jLabel2");

        tablacambio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "uno", "Title 2", "Title 3", "Title 4", "cinco"
            }
        ));
        jScrollPane1.setViewportView(tablacambio);

        javax.swing.GroupLayout paneltablaLayout = new javax.swing.GroupLayout(paneltabla);
        paneltabla.setLayout(paneltablaLayout);
        paneltablaLayout.setHorizontalGroup(
            paneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        paneltablaLayout.setVerticalGroup(
            paneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lclave_venta)
                            .addComponent(lc_claveventa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lid_usuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tamañodedatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addComponent(ltotale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paneltabla, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ldarcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotale)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ldarcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lclave_venta)
                    .addComponent(lid_usuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamañodedatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lc_claveventa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneltabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdinerorecibidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdinerorecibidoKeyReleased
       int clavetecla=evt.getExtendedKeyCode();
       
     if(moneda(txtdinerorecibido.getText())==true){
        if(txtdinerorecibido.getText().isEmpty()){
            System.out.println("nafa");
            ldarcambio.setVisible(false);
            lcambio.setVisible(false);
        }
        else{
            cambio();
        }
         if(clavetecla==16){

         this.setVisible(false);

        }
    }
    }//GEN-LAST:event_txtdinerorecibidoKeyReleased

    private void txtdinerorecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdinerorecibidoActionPerformed
        String ttrecibido=  txtdinerorecibido.getText();
        double tota=Double.parseDouble(ltotale.getText());
        if(ttrecibido.isEmpty()==false){
            if(Double.parseDouble(ttrecibido)>=tota){
        System.out.println("hacer nada");
       
        lc_claveventa.setText(fn.fechaventa()+fn.horaventa());
        
        int ltamma=Integer.parseInt(tamañodedatos.getText());
        int cidus= Integer.parseInt(lid_usuarioc.getText());
        String clave_venta=lc_claveventa.getText();
        guardarventa(cidus,clave_venta);
        for (int w =0; w<ltamma; w++) {
            String cctclave=tablacambio.getModel().getValueAt(w, 0).toString();
            int cctcantidad = Integer.parseInt(tablacambio.getModel().getValueAt(w, 1).toString());
            vn.setId_ropa(cctclave);
            vn.setCantidad(cctcantidad);
            vn.setId_venta(clave_venta+cidus);
            vm.guardar_detalleventa(vn);
        }
        lcambio.setVisible(false);
        
        extraerdatos(ltamma,clave_venta);
        valorventa=5;
        txtdinerorecibido.setText(null);
        ldarcambio.setVisible(false);
        lcambio.setVisible(false);
        this.setVisible(false);
        recibo2.setVisible(false);
        
 
        
        recibo2.imprimirrecibo();
        
        
        //   limpiar(lta);
   
            }
        }
    }//GEN-LAST:event_txtdinerorecibidoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         txtdinerorecibido.setText(null);
              lcambio.setVisible(false);
               ldarcambio.setVisible(false);
     
              
    }//GEN-LAST:event_formWindowClosed

    private void txtdinerorecibidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdinerorecibidoKeyTyped
               
                
                val.textoynumero(evt, txtdinerorecibido);
    }//GEN-LAST:event_txtdinerorecibidoKeyTyped

    boolean moneda(String cajatexto){
     Pattern p=Pattern.compile("(([0-9]|[0-9][.][0-9])+)");
     Matcher m=p.matcher(cajatexto);
     return m.matches();
     }
    
    public static int valorventa;

    public void extraerdatos(int tamama,String clave){
       
      for (int qr =0; qr<tamama; qr++) {
              System.out.println("Q= "+ qr);
            String ctclave=tablacambio.getModel().getValueAt(qr, 0).toString();
            String ctcantidad = tablacambio.getModel().getValueAt(qr, 1).toString();
            String ctdescripcion=tablacambio.getModel().getValueAt(qr, 2).toString();
            String ctprecio =tablacambio.getModel().getValueAt(qr, 3).toString();
            String ctotale= tablacambio.getModel().getValueAt(qr, 4).toString();
              String descripcion=ctdescripcion+"  ("+ctcantidad+"  X "+"$"+ctprecio+")";
            recibo2.recibo1.listareci.add(qr,descripcion+" ... "+"  $"+ctotale);
           
    }
             recibo2.recibo1.lcambio.setText("CAMBIO: $"+lcambio.getText());
            recibo2.recibo1.lfolio.setText("FOLIO:"+clave);
            recibo2.recibo1.ldinerorecibido.setText("DINERO RECIBIDO: $"+txtdinerorecibido.getText());
            recibo2.recibo1.ltotal.setText("TOTAL: $"+ltotale.getText());
            recibo2.recibo1.lvendedor.setText("V :"+nombreus);
             recibo2.recibo1.lfecha.setText("FECHA  "+fn.fechaactual()+"   HORA  "+fn.hora_completa());
    
      
    }
    
    public void limpiar(int ytam){
       
        for (int fd = 0; fd <ytam ; fd++) {
            tablacambio.setValueAt(null,fd,0);
            tablacambio.setValueAt(null,fd,1);
            tablacambio.setValueAt(null,fd,2);
            tablacambio.setValueAt(null,fd,3);
            tablacambio.setValueAt(null,fd,4);
            
        }
         
    }
    public void cambio(){
   double p= Double.parseDouble(ltotale.getText());
   double cr= Double.parseDouble(txtdinerorecibido.getText());
 
    if(cr>=p){
   
       double cb= cr-p;
       ldarcambio.setVisible(true);
       lcambio.setVisible(true);
       lcambio.setText(Double.toString(cb));
   }
    if(cr<p){
           ldarcambio.setVisible(false);
       lcambio.setVisible(false);
    }
}
    public void guardarventa(int vcidus,String claveventa){
         vn.setId_venta(claveventa+vcidus);
         vn.setId_usuario(vcidus);
         vn.setFecha(fn.fechaactual());
         vn.setHora(fn.hora_completa());
         vn.setTotal_venta(ltotale.getText());
         vm.guardar_venta(vn);
       
         
     }
 public static int valor;
       public void extraerdatostabla(){
        // DefaultTableModel modeloTabla = new DefaultTableModel();
        //tablaD.setModel(modeloTabla);
       int textraer = Integer.parseInt(tamañodedatos.getText());
       
  
      
        /*
          for (int qr =0; qr< textraer; qr++) {
              System.out.println("Q= "+ qr);
            String tclave=tabla_ventas.getModel().getValueAt(qr, 0).toString();
            int tcantidad = Integer.parseInt(tabla_ventas.getModel().getValueAt(qr, 1).toString());
            String tdescripcion=tabla_ventas.getModel().getValueAt(qr, 2).toString();
            double tprecio = Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 3).toString());
            double totale= Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 4).toString());
            cambio.tablacambio.setValueAt(tclave, qr, 0);
            cambio.tablacambio.setValueAt(tcantidad, qr, 1);
            cambio.tablacambio.setValueAt(tdescripcion, qr, 2);
            cambio.tablacambio.setValueAt(tprecio, qr, 3);
            cambio.tablacambio.setValueAt(totale, qr, 4);
            
         
        
    }*/
          
   }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lc_claveventa;
    public javax.swing.JLabel lcambio;
    private javax.swing.JLabel lclave_venta;
    public javax.swing.JLabel ldarcambio;
    public javax.swing.JLabel lid_usuarioc;
    public javax.swing.JLabel ltotale;
    public javax.swing.JPanel paneltabla;
    public javax.swing.JTable tablacambio;
    public javax.swing.JLabel tamañodedatos;
    public javax.swing.JTextField txtdinerorecibido;
    // End of variables declaration//GEN-END:variables
}
