/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Apartado;
import clases.Venta;
import clasesmetodos.Venta_metodos;
import javax.swing.table.DefaultTableModel;
import metodosvarios.Fecha;
import clasesmetodos.Apartado_metodos;
import static interfaces.Cambio.nombreus;


/**
 *
 * @author 
 */
public class Cambio_apartado2 extends javax.swing.JFrame {
Recibos recibo2= new Recibos();
DefaultTableModel modeloTablaCambio;
Venta vn=new Venta();
Fecha fn= new Fecha();
Venta_metodos vm= new Venta_metodos();
Apartado_metodos apdao= new Apartado_metodos();
Apartado ap= new Apartado();
Apartado appago= new Apartado();
public static String id_client=null;
public static String afechainicio=null;
public static String afechafin=null;
public static String id_apartados=null;
public static int tipodecambio=0;


public static String afecha=null;
public static String avendedor= null;
public static  String acliente=null;

    /**
     * Creates new form Cambio_apartado
     */
    public Cambio_apartado2() {
        initComponents();
          this.setLocationRelativeTo(null);
        ldarcambio1.setVisible(false);
       lcambio1.setVisible(false);
        String encabezado[]={"CLAVE","CANTIDAD"+"DESCRIPCION","PRECIO UNITARIO","SUBTOTAL"}; String datos[][]={};
         modeloTablaCambio=new DefaultTableModel(datos,encabezado);
         ltotale1.setVisible(false);
         paneltabla1.setVisible(false);
                 
         vmensaje.setVisible(false);
         lid_apartadoAP.setVisible(false);
         lc_claveventa1.setVisible(false);
         lid_usuarioc1.setVisible(false);
         tamañodedatos1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        txtdinerorecibido1 = new javax.swing.JTextField();
        lcambio1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ldarcambio1 = new javax.swing.JLabel();
        paneltabla1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacambio1 = new javax.swing.JTable();
        lid_usuarioc1 = new javax.swing.JLabel();
        tamañodedatos1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ltotale1 = new javax.swing.JLabel();
        vmensaje = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lmensajeabono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmontoabonar = new javax.swing.JTextField();
        lid_apartadoAP = new javax.swing.JLabel();
        lc_claveventa1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtdinerorecibido1.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        txtdinerorecibido1.setForeground(new java.awt.Color(51, 0, 102));
        txtdinerorecibido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdinerorecibido1.setToolTipText("");
        txtdinerorecibido1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtdinerorecibido1.setCaretColor(new java.awt.Color(204, 0, 0));
        txtdinerorecibido1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtdinerorecibido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdinerorecibido1ActionPerformed(evt);
            }
        });
        txtdinerorecibido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdinerorecibido1KeyReleased(evt);
            }
        });

        lcambio1.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        lcambio1.setForeground(new java.awt.Color(0, 204, 0));
        lcambio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DINERO RECIBIDO:");

        ldarcambio1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ldarcambio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldarcambio1.setText("CAMBIO:");

        tablacambio1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "uno", "Title 2", "Title 3", "Title 4", "cinco"
            }
        ));
        jScrollPane2.setViewportView(tablacambio1);

        lid_usuarioc1.setText("jLabel2");

        tamañodedatos1.setText("0");

        javax.swing.GroupLayout paneltabla1Layout = new javax.swing.GroupLayout(paneltabla1);
        paneltabla1.setLayout(paneltabla1Layout);
        paneltabla1Layout.setHorizontalGroup(
            paneltabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneltabla1Layout.createSequentialGroup()
                        .addComponent(lid_usuarioc1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(tamañodedatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltabla1Layout.setVerticalGroup(
            paneltabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltabla1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(paneltabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamañodedatos1)
                    .addComponent(lid_usuarioc1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        ltotale1.setBackground(new java.awt.Color(153, 255, 153));
        ltotale1.setForeground(new java.awt.Color(255, 255, 255));
        ltotale1.setText("5");

        vmensaje.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EL MONTO A A BONAR ES MAYOR A LA CANTIDAD A PAGAR");

        lmensajeabono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lmensajeabono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmensajeabono.setText("DEBERIA COLOCAR: ");

        javax.swing.GroupLayout vmensajeLayout = new javax.swing.GroupLayout(vmensaje);
        vmensaje.setLayout(vmensajeLayout);
        vmensajeLayout.setHorizontalGroup(
            vmensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vmensajeLayout.createSequentialGroup()
                .addComponent(lmensajeabono, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(vmensajeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        vmensajeLayout.setVerticalGroup(
            vmensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vmensajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmensajeabono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(ltotale1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ltotale1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MONTO A ABONAR:");

        txtmontoabonar.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        txtmontoabonar.setForeground(new java.awt.Color(51, 0, 102));
        txtmontoabonar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmontoabonar.setToolTipText("");
        txtmontoabonar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtmontoabonar.setCaretColor(new java.awt.Color(204, 0, 0));
        txtmontoabonar.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtmontoabonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoabonarActionPerformed(evt);
            }
        });
        txtmontoabonar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontoabonarKeyReleased(evt);
            }
        });

        lid_apartadoAP.setText("0");

        lc_claveventa1.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(paneltabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lc_claveventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdinerorecibido1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lid_apartadoAP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))
                            .addComponent(lcambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmontoabonar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(ldarcambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmontoabonar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdinerorecibido1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ldarcambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lid_apartadoAP)
                .addGap(3, 3, 3)
                .addComponent(lc_claveventa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneltabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdinerorecibido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdinerorecibido1ActionPerformed
       
        
        int yywywywy=0;
        yywywywy=Integer.parseInt(lid_apartadoAP.getText());
       
        if(yywywywy==1){
            String clave_apartad="d";
             pago_apartado(lc_claveventa1.getText(),Double.parseDouble(txtmontoabonar.getText()));
              tipodecambio=1;
        }
        if( yywywywy==0){
            tipodecambio=2;
        

        lc_claveventa1.setText("A"+fn.fechaventa()+fn.horaventa());
        
        
       // recibo2.setVisible(false);
        int ltamma=Integer.parseInt(tamañodedatos1.getText());
        int cidus= Integer.parseInt(lid_usuarioc1.getText());
        String clave_venta=lc_claveventa1.getText();
        guardarapartado(cidus,clave_venta);
        double apc_pagoabonar=Double.parseDouble(txtmontoabonar.getText());
        pago_apartado(clave_venta,apc_pagoabonar);
   
        for (int w =0; w<ltamma; w++) {
            String cctclave=tablacambio1.getModel().getValueAt(w, 0).toString();
            int cctcantidad = Integer.parseInt(tablacambio1.getModel().getValueAt(w, 1).toString());
           
           
            ap.setId_ropa(cctclave);
            ap.setCantidad_apartado(cctcantidad);
            ap.setId_apartado(clave_venta);
            apdao.guardardetalle_apartado(ap);
        }
         int ltamama=Integer.parseInt(tamañodedatos1.getText());
        extraerdatos(ltamama,clave_venta);
        recibo2.imprimirrecibo();
        limpiar(ltamama);
        valorapartado=5;
        txtdinerorecibido1.setText(null);
        ldarcambio1.setVisible(false);
        lcambio1.setVisible(false);
        vmensaje.setVisible(false);
        
        }
        
        if(Double.parseDouble(ltotale1.getText())==Double.parseDouble(txtmontoabonar.getText())){
            Apartado apar11= new Apartado();
            Apartado_metodos am11= new Apartado_metodos();
            apar11.setEstado_apartado(5);
            apar11.setId_apartado(lc_claveventa1.getText());
            
           am11. modifica_estado_apartado( apar11);
        }
        this.setVisible(false);
       
        
        
        

        
        
        txtmontoabonar.setText(null);
    }//GEN-LAST:event_txtdinerorecibido1ActionPerformed

    private void txtdinerorecibido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdinerorecibido1KeyReleased
        int clavetecla=evt.getExtendedKeyCode();

        if(txtdinerorecibido1.getText().isEmpty()){
            System.out.println("nafa");
            ldarcambio1.setVisible(false);
            lcambio1.setVisible(false);
        }
        else{
            cambio();
        }
        if(clavetecla==16){

            this.setVisible(false);

        }

    }//GEN-LAST:event_txtdinerorecibido1KeyReleased

    private void txtmontoabonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoabonarActionPerformed
        
 
System.out.print(id_client);
        System.out.print(afechainicio);
        System.out.print(afechafin);
    }//GEN-LAST:event_txtmontoabonarActionPerformed

    private void txtmontoabonarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoabonarKeyReleased
       if(txtmontoabonar.getText().isEmpty()==false){
           
       
       double abono=Double.parseDouble(ltotale1.getText());
       String sabono=txtmontoabonar.getText();
       if(sabono==null){
           
         int twwwwww=8;
       }
       else{
           double ssabono=Double.parseDouble(sabono);
           if( ssabono>abono || ssabono< 1){
               txtmontoabonar.setText(null);
               lmensajeabono.setText("DEBERÍA COLOCAR MAXIMO LA CANTIDAD DE: $ "+abono);
               vmensaje.setVisible(true);
               
               
           
           }
            if(ssabono<abono ){
                 vmensaje.setVisible(false);
            }
       
       }}
      
    }//GEN-LAST:event_txtmontoabonarKeyReleased
public static int valorapartado;


public void pago_apartado(String clav_ven,double pagoapa_a){
       appago.setId_apartado(clav_ven);
                 appago.setPago_apartado(pagoapa_a);
                 appago.setFecha_pago(fn.fechaactual());
                 appago.setHora_pago(fn.hora_completa());
                 apdao.pagos_apartado(appago);
                
}
  public void guardarapartado(int vcidus,String claveventa){
         ap.setId_apartado(claveventa);
         ap.setId_usuario(vcidus);
        ap.setId_cliente(Integer.parseInt(id_client));
       ap.setFecha_inicio(afechainicio);
        ap.setFecha_fin(afechafin);
         ap.setHora(fn.hora_completa());
         ap.setTotal_apartado(Double.parseDouble(ltotale1.getText()));
         ap.setEstado_apartado(0);
         apdao.guardar_apartado(ap);
         
         
  }
    
  /*
  public void extraerdatos(int tamama){
       
      for (int qr =0; qr<tamama; qr++) {
              System.out.println("Q= "+ qr);
            String ctclave=tablacambio1.getModel().getValueAt(qr, 0).toString();
            String ctcantidad = tablacambio1.getModel().getValueAt(qr, 1).toString();
            String ctdescripcion=tablacambio1.getModel().getValueAt(qr, 2).toString();
            String ctprecio =tablacambio1.getModel().getValueAt(qr, 3).toString();
            String ctotale= tablacambio1.getModel().getValueAt(qr, 4).toString();
              String descripcion= ctclave+" "+ctdescripcion+"  "+ctcantidad+" x "+"$"+ctprecio;
            recibo2.recibo1.listareci.add(qr,descripcion+"  ...............  "+"$ "+ctotale);
            
            
           // recibo2.recibo1.tablarecibo.setValueAt(ctclave+" "+ctcantidad+"x"+"$"+ctprecio, qr, 0);
           // recibo2.recibo1.tablarecibo.setValueAt(ctdescripcion, qr, 1);
           // recibo2.recibo1.tablarecibo.setValueAt(ctotale, qr, 2); 
         
    }
      
    
      
    }*/
    public void extraerdatos(int tamama,String clave){
       
      for (int qr =0; qr<tamama; qr++) {
              System.out.println("Q= "+ qr);
            String ctclave=tablacambio1.getModel().getValueAt(qr, 0).toString();
            String ctcantidad = tablacambio1.getModel().getValueAt(qr, 1).toString();
            String ctdescripcion=tablacambio1.getModel().getValueAt(qr, 2).toString();
            String ctprecio =tablacambio1.getModel().getValueAt(qr, 3).toString();
            String ctotale= tablacambio1.getModel().getValueAt(qr, 4).toString();
              String descripcion=ctdescripcion+"  ("+ctcantidad+"  X "+"$"+ctprecio+")";
            recibo2.recibo1.listareci.add(qr,descripcion+" ... "+"  $"+ctotale);
           
    }
             recibo2.recibo1.lcambio.setText("CAMBIO: $"+lcambio1.getText());
              recibo2.recibo1.lpago.setText("ABONO:$"+txtmontoabonar.getText());
            recibo2.recibo1.lfolio.setText("ID APARTADO:"+clave);
            recibo2.recibo1.ldinerorecibido.setText("DINERO RECIBIDO: $"+txtdinerorecibido1.getText());
            recibo2.recibo1.ltotal.setText("TOTAL: $"+ltotale1.getText());
            recibo2.recibo1.lvendedor.setText("V :"+avendedor);
             recibo2.recibo1.lcliente.setText(acliente);
             recibo2.recibo1.lfecha.setText(afecha);
    
      
    }
    
    public void limpiar(int ytam){
       
        for (int fd = 0; fd <ytam ; fd++) {
            tablacambio1.setValueAt(null,fd,0);
            tablacambio1.setValueAt(null,fd,1);
            tablacambio1.setValueAt(null,fd,2);
            tablacambio1.setValueAt(null,fd,3);
            tablacambio1.setValueAt(null,fd,4);
            
        }
         
    }
    public void cambio(){
   double p= Double.parseDouble(txtmontoabonar.getText());
   double cr= Double.parseDouble(txtdinerorecibido1.getText());
 
    if(cr>=p){
   
       double cb= cr-p;
       ldarcambio1.setVisible(true);
       lcambio1.setVisible(true);
       lcambio1.setText(Double.toString(cb));
   }
    if(cr<p){
           ldarcambio1.setVisible(false);
       lcambio1.setVisible(false);
    }
}
    public void guardarventa(int vcidus,String claveventa){
         vn.setId_venta(claveventa+vcidus);
         vn.setId_usuario(vcidus);
         vn.setFecha(fn.fechaactual());
         vn.setHora(fn.hora_completa());
         vn.setTotal_venta(ltotale1.getText());
         vm.guardar_venta(vn);
       
         
     }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambio_apartado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambio_apartado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambio_apartado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambio_apartado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambio_apartado2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    public javax.swing.JLabel lc_claveventa1;
    public javax.swing.JLabel lcambio1;
    public javax.swing.JLabel ldarcambio1;
    public javax.swing.JLabel lid_apartadoAP;
    public javax.swing.JLabel lid_usuarioc1;
    private javax.swing.JLabel lmensajeabono;
    public javax.swing.JLabel ltotale1;
    public javax.swing.JPanel paneltabla1;
    public javax.swing.JTable tablacambio1;
    public javax.swing.JLabel tamañodedatos1;
    public javax.swing.JTextField txtdinerorecibido1;
    public javax.swing.JTextField txtmontoabonar;
    private javax.swing.JPanel vmensaje;
    // End of variables declaration//GEN-END:variables
}
