/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import clases.Apartado;
import clasesmetodos.Apartado_metodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Cliente_buscar extends javax.swing.JFrame {
Apartado aparta= new Apartado();
Apartado_metodos apartadao = new Apartado_metodos();
public static String  valor_clientes=null;
public static String nombre_cliente=null;
public static int v_consulta=0;
Validaciones valida = new Validaciones();
Otros otros= new Otros();
//vconsulta=5 es para el solo sin hacer nada
//vconsulta=10 es para cambio_apartado
//vconsulta=15 es para Apartado_pagos



    /**
     * Creates new form Cliente_buscar
     */
    public Cliente_buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
       // this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtbuscarcliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtnombrec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttelc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtamc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnregistrarc = new javax.swing.JButton();
        btnborrarclientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarclienteActionPerformed(evt);
            }
        });
        txtbuscarcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarclienteKeyReleased(evt);
            }
        });

        jLabel1.setText("BUSCAR");

        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_clientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BUSCAR CLIENTES", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtnombrec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnombrec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrecKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE");

        txtapc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtapc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapcKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APELLIDO PATERNO");

        txttelc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txttelc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelcKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NUMERO DE TELEFONO");

        txtamc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtamc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtamc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamcKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("APELLIDO MATERNO");

        btnregistrarc.setText("REGISTRAR CLIENTE");
        btnregistrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarcActionPerformed(evt);
            }
        });

        btnborrarclientes.setText("BORRAR");
        btnborrarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarclientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombrec, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtamc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttelc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnregistrarc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnborrarclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtapc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtamc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txttelc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnregistrarc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnborrarclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRAR CLIENTE", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarcActionPerformed
       guardar_cliente();
     
    }//GEN-LAST:event_btnregistrarcActionPerformed

    private void txtbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarclienteActionPerformed

    private void txtbuscarclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarclienteKeyReleased
        String buscar=null;
        
        buscar= txtbuscarcliente.getText();
         clientespor(tabla_clientes, buscar);
        
    }//GEN-LAST:event_txtbuscarclienteKeyReleased

    private void tabla_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clientesMouseClicked
       
         int filaInicio = tabla_clientes.getSelectedRow();
            int numFS = tabla_clientes.getSelectedRowCount();
            ArrayList<String> listId = new ArrayList();
            String id = "";
            if (filaInicio >= 0) {
                for (int i = 0; i < numFS; i++) {
                    id = String.valueOf(tabla_clientes.getValueAt(i + filaInicio, 0));
                    listId.add(id);
                    
                }
                System.out.println(listId);
                 rellenar_cliente(id);
                valor_clientes=id;
               nombre_cliente=txtnombrec.getText()+ " "+txtapc.getText()+" "+txtamc.getText();
                 
                 // txtcodigo.setEditable(false);
                
               
            } else {
              JOptionPane.showMessageDialog(null, "debes seleccionar solo una fila");
              valor_clientes=null;
              nombre_cliente=null;
            }  
             if(v_consulta==10 || v_consulta==15){
                 this.setVisible(false);
             }
    }//GEN-LAST:event_tabla_clientesMouseClicked

    private void btnborrarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarclientesActionPerformed
       limpiarcliente();
        System.out.println("nombre cliente"+nombre_cliente);
        System.out.println("id cliente"+valor_clientes);
        
    }//GEN-LAST:event_btnborrarclientesActionPerformed

    private void txtnombrecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecKeyTyped
      valida.texto(evt, txtnombrec , 15);
    }//GEN-LAST:event_txtnombrecKeyTyped

    private void txtapcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapcKeyTyped
         valida.texto(evt,txtapc,15);// TODO add your handling code here:
    }//GEN-LAST:event_txtapcKeyTyped

    private void txtamcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamcKeyTyped
         valida.texto(evt,txtamc,15);
    }//GEN-LAST:event_txtamcKeyTyped

    private void txttelcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelcKeyTyped
    valida.numeros(evt,txttelc, 10);
    }//GEN-LAST:event_txttelcKeyTyped
 
    public void limpiarcliente(){
   txtamc.setText(null);
   txtapc.setText(null);
   txtbuscarcliente.setText(null);
   txtnombrec.setText(null);
   txttelc.setText(null);
           
           
}
    public void rellenar_cliente(String idc){
         txtamc.setText(apartadao.clientesTDA(idc).getAm_c());
   txtapc.setText(apartadao.clientesTDA(idc).getAp_c());
   
   txtnombrec.setText(apartadao.clientesTDA(idc).getNombre_c());
   txttelc.setText(apartadao.clientesTDA(idc).getTelefono_c());
    }
    
    public void guardar_cliente(){
    String nom= otros.novacio(txtnombrec.getText());
    String ap=otros.novacio( txtapc.getText());
    String am= otros.novacio(txtamc.getText());
    String telefono=otros.novacio(txttelc.getText());
    String vali[]={"","","",""};
    String me="N";
    if(valida.vtexto1(nom)==false){
        me="ESCRIBA ALMENOS 3 LETRAS EN EL NOMBRE";
         vali[0]=me;
    }
     if(valida.vtexto1(ap)==false){
        me="ESCRIBA ALMENOS TRES LETRAS EN EL APELLIDO PATERNO";
         vali[1]=me;
    }
     if(valida.vtexto1(am)==false){
        me="ESCRIBA ALMENOS TRES LETRAS EN EL APELLIDO MATERNO";
         vali[2]=me;
    }
     if(valida.vtel(telefono)==false){
        me="ESCRIBA 10 NUMEROS ENTEROS PARA EL TELEFONO";
         vali[3]=me;
    }
     if(me.equals("N")){
    
        aparta.setId_cliente(0);
        aparta.setNombre_c(nom);
        aparta.setAp_c(ap);
        aparta.setAm_c(am);
        aparta.setTelefono_c(telefono);
        
        
        apartadao.guardar_cientes(aparta);
         limpiarcliente();
         JOptionPane.showMessageDialog(null,"SE HA GUARDADO EL CLIENTE");
         
     }else{
         JOptionPane.showMessageDialog(null,vali);
     }
     
    }
    public void clientespor(JTable tablaD,String t) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("CLAVE");
       modeloTabla.addColumn("NOMBRE");
       modeloTabla.addColumn("APELLIDO PATERNO");
       modeloTabla.addColumn("APELLIDO MATERNO");
        modeloTabla.addColumn("TELEFONO");
  
      
    

        Object[] columna = new Object[5];
        int numReg=apartadao.clientespor(t).size();

        for (int i = 0; i < numReg; i++) {
        
          
          columna[0] =apartadao.clientespor(t).get(i).getId_cliente();
          columna[1] =apartadao.clientespor(t).get(i).getNombre_c();
          columna[2] = apartadao.clientespor(t).get(i).getAp_c();
          columna[3] = apartadao.clientespor(t).get(i).getAm_c();
          columna[4]=apartadao.clientespor(t).get(i).getTelefono_c();
      
            modeloTabla.addRow(columna);
        }
        
     
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnborrarclientes;
    public javax.swing.JButton btnregistrarc;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tabla_clientes;
    private javax.swing.JTextField txtamc;
    private javax.swing.JTextField txtapc;
    public javax.swing.JTextField txtbuscarcliente;
    private javax.swing.JTextField txtnombrec;
    private javax.swing.JTextField txttelc;
    // End of variables declaration//GEN-END:variables
}
