/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import java.util.HashSet;
import java.util.Set;
import javax.swing.JTable;
import metodosvarios.Fecha;


/**
 *
 * @author 
 */
public class Inicio extends javax.swing.JFrame {
Cambio cam= new Cambio();
Cliente_buscar cliebus= new Cliente_buscar();
Cambio_apartado2 cb= new Cambio_apartado2();
Aparatado_ropa apropa= new Aparatado_ropa(); 

Fecha fn= new Fecha();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
          this.setExtendedState(Inicio.MAXIMIZED_BOTH);
      ltipousuario.setVisible(false);
           
      
        //   mostraradmin();
       
        
      //  vocionesapartado.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnprenda = new javax.swing.JButton();
        vropaopciones = new javax.swing.JPanel();
        btningresar1 = new javax.swing.JButton();
        btnreporteventas = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnprenda1 = new javax.swing.JButton();
        vocionesapartado = new javax.swing.JPanel();
        btningresar5 = new javax.swing.JButton();
        btningresar7 = new javax.swing.JButton();
        btningresar6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnregistrarproducto = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btninventario = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnusuarios = new javax.swing.JButton();
        pantalla = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        ltipousuario = new javax.swing.JLabel();
        claveusuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lnombre_us2 = new javax.swing.JLabel();
        lnombre_us = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        btnprenda.setBackground(new java.awt.Color(255, 255, 255));
        btnprenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnprenda.setText("VENTAS");
        btnprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprendaActionPerformed(evt);
            }
        });

        vropaopciones.setBackground(new java.awt.Color(153, 255, 153));

        btningresar1.setBackground(new java.awt.Color(0, 255, 0));
        btningresar1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btningresar1.setText("REALIZAR VENTA");
        btningresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar1ActionPerformed(evt);
            }
        });

        btnreporteventas.setBackground(new java.awt.Color(51, 255, 0));
        btnreporteventas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnreporteventas.setText("REPORTE VENTAS");
        btnreporteventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteventasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vropaopcionesLayout = new javax.swing.GroupLayout(vropaopciones);
        vropaopciones.setLayout(vropaopcionesLayout);
        vropaopcionesLayout.setHorizontalGroup(
            vropaopcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btningresar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnreporteventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vropaopcionesLayout.setVerticalGroup(
            vropaopcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vropaopcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btningresar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnreporteventas)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnprenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vropaopciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vropaopciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 153));

        btnprenda1.setBackground(new java.awt.Color(255, 255, 255));
        btnprenda1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnprenda1.setText("APARTADO");
        btnprenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprenda1ActionPerformed(evt);
            }
        });

        vocionesapartado.setBackground(new java.awt.Color(153, 255, 153));

        btningresar5.setBackground(new java.awt.Color(51, 255, 0));
        btningresar5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btningresar5.setText("REALIZAR APARTADO");
        btningresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar5ActionPerformed(evt);
            }
        });

        btningresar7.setBackground(new java.awt.Color(51, 255, 0));
        btningresar7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btningresar7.setText("REPORTE APARTADOS");
        btningresar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar7ActionPerformed(evt);
            }
        });

        btningresar6.setBackground(new java.awt.Color(51, 255, 0));
        btningresar6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btningresar6.setText("DETALLE PAGOS");
        btningresar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vocionesapartadoLayout = new javax.swing.GroupLayout(vocionesapartado);
        vocionesapartado.setLayout(vocionesapartadoLayout);
        vocionesapartadoLayout.setHorizontalGroup(
            vocionesapartadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btningresar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btningresar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btningresar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vocionesapartadoLayout.setVerticalGroup(
            vocionesapartadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vocionesapartadoLayout.createSequentialGroup()
                .addComponent(btningresar5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btningresar6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btningresar7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnprenda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vocionesapartado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnprenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vocionesapartado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));

        btnregistrarproducto.setBackground(new java.awt.Color(255, 255, 255));
        btnregistrarproducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnregistrarproducto.setText("REGISTRAR ROPA");
        btnregistrarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnregistrarproducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnregistrarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 255, 153));

        btninventario.setBackground(new java.awt.Color(255, 255, 255));
        btninventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btninventario.setText("INVENTARIO");
        btninventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btninventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(153, 255, 153));

        btnusuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusuarios.setText("USUARIOS");
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pantalla.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));

        ltipousuario.setText("USUARIO");

        claveusuario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        claveusuario.setForeground(new java.awt.Color(255, 255, 255));
        claveusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claveusuario.setText("1");

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lnombre_us2.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        lnombre_us2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lnombre_us.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lnombre_us.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(lnombre_us, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(lnombre_us2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lnombre_us2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lnombre_us, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(ltipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(claveusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ltipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(claveusuario)
                .addGap(67, 67, 67))
        );

        pantalla.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pantalla, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprendaActionPerformed
         
        
        
        
        if(vropaopciones.isVisible()==false){
            vropaopciones.setVisible(true);
            if( rr.isShowing()==false){
           btnregistrarproducto.setEnabled(true); 
       }
      
        }
        else{
             vropaopciones.setVisible(false);
        }
     
       
    }//GEN-LAST:event_btnprendaActionPerformed
Ventas_ropa vr= new Ventas_ropa();
    private void btningresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar1ActionPerformed
       try{
             Inicio in= new Inicio();
       if( vr.isVisible()==false){
              String vidus=claveusuario.getText();
        vropaopciones.setVisible(false);
        pantalla.add(vr);
    int ancho=pantalla.getWidth();
    int alto=pantalla.getHeight();
    Cambio.nombreus=this.lnombre_us.getText();
  vr.setSize((ancho-5),(alto-5));
  vr.lv_idus.setText(vidus);

            
           vr.setVisible(true);
        }
        else{
            vr.setVisible(false);
        }
       } catch(Exception e){
           System.out.println(e);
       }
      
     
    }//GEN-LAST:event_btningresar1ActionPerformed
  Registro_ropa rr =new Registro_ropa ();
    private void btnregistrarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarproductoActionPerformed
     try{
        if( rr.isVisible()==false){
          pantalla.add(rr);
    int ancho=pantalla.getWidth();
    int alto=pantalla.getHeight();
    
  rr.setSize((ancho-5),(alto-5));
 
            
           rr.setVisible(true);
        }
        else{
            rr.setVisible(false);
        }
       
      } catch(Exception e){
           System.out.println(e);
       }
        
    }//GEN-LAST:event_btnregistrarproductoActionPerformed
  Usuarios us =new Usuarios();
    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
      try{
        
        if( us.isVisible()==false){
     pantalla.add(us);
   // int ancho=pantalla.getWidth();
  //  int alto=pantalla.getHeight();
    
  //rr.setSize((ancho-5),(alto-5));
 
            
           us.setVisible(true);
        }
        else{
            us.setVisible(false);
        }      
        } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnusuariosActionPerformed
  Inventario in=  new Inventario();
    private void btninventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarioActionPerformed
        try{
        if( in.isVisible()==false){
             pantalla.add(in);
    int ancho=pantalla.getWidth();
    int alto=pantalla.getHeight();
    
  in.setSize((ancho-5),(alto-5));
 
           in.setVisible(true);
        }
        else{
            in.setVisible(false);
        }
         } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btninventarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      try{
        
        int cvvetntas=cam.valorventa;
       String id_clienteap= cliebus.valor_clientes;
        String nombre_clienteap=cliebus.nombre_cliente;
        int cappr=cb.valorapartado;
     // int etadatopagosapar=  cb.aparatadopagos;
     // if(etadatopagosapar==1){
         // apagos.actualizardatospagos(); 
     // }
    int tipoapar= cb.tipodecambio;
    if(tipoapar==1){
       apagos.mostra();
        cb.tipodecambio=0;
    }
        if(id_clienteap!=null){
            
            int tipoconsul= cliebus.v_consulta;
            if(tipoconsul==10){
                apropa.txtnomclientea.setText(nombre_clienteap);
            apropa.lid_cliente.setText(id_clienteap);
            apropa.Atxtcodigo.setEditable(true);
            
            }
            if(tipoconsul==15){
            apagos.txtnombrecliente_pagosa.setText(nombre_clienteap);
            apagos.lid_clienteapartadopago.setText(id_clienteap);
            apagos.clientespor(apagos.tabla_pagos,id_clienteap);
            // apagos.limpiar();
            apagos.vbuscarclientes.setVisible(true);
           
            }
            cliebus.v_consulta=0;
        }
        System.out.println("cventas= "+cvvetntas);
      if(cvvetntas==5){
     vr.limpiartabla();
     vr.lpago.setText("0");
      vr. larticulos.setText("0");
         cam.valorventa=0; 
        
       
        
       
      }
       if(cappr==5){
            apropa.limpiarapatado();
              apropa.txtnomclientea.setText(null);
            apropa.lid_cliente.setText("0");
            apropa.Atxtcodigo.setEditable(false);
            cb.valorapartado=0;
        }
       if(cappr==10){
            apropa.limpiarapatado();
              apropa.txtnomclientea.setText(null);
            apropa.lid_cliente.setText("0");
            apropa.Atxtcodigo.setEditable(false);
            cb.valorapartado=0;
        }
         } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_formWindowActivated
Reporte_ventas rv= new Reporte_ventas();
    private void btnreporteventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteventasActionPerformed
try{
        if( rv.isVisible()==false){
             pantalla.add(rv);
    int ancho=pantalla.getWidth();
    int alto=pantalla.getHeight();
    
  rv.setSize((ancho-5),(alto-5));

 vropaopciones.setVisible(false);
           rv.setVisible(true);
        }
        else{
            rv.setVisible(false);
        }
        } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnreporteventasActionPerformed

    private void btningresar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar6ActionPerformed
try{
        if( apagos.isVisible()==false){
             pantalla.add(apagos);
        int ancho=pantalla.getWidth();
        int alto=pantalla.getHeight();

        apagos.setSize((ancho-5),(alto-5));

        
        vocionesapartado.setVisible(false);
           apagos.setVisible(true);
        }
        else{
            apagos.setVisible(false);
        }
 } catch(Exception e){
           System.out.println(e);
       }
       
    }//GEN-LAST:event_btningresar6ActionPerformed
Reporteapartado rap=new Reporteapartado();
    private void btningresar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar7ActionPerformed

        try{
        if( rap.isVisible()==false){
            pantalla.add(rap);
    int ancho=pantalla.getWidth();
    int alto=pantalla.getHeight();
    
  rap.setSize((ancho-5),(alto-5));
 
vocionesapartado.setVisible(false);
           rap.setVisible(true);
           
        }
        else{
           rap.setVisible(false);
        }
        
         } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btningresar7ActionPerformed

    private void btningresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar5ActionPerformed
        try{
        if( apropa.isVisible()==false){
            pantalla.add(apropa);
        int ancho=pantalla.getWidth();
        int alto=pantalla.getHeight();

        apropa.setSize((ancho-5),(alto-5));
       String fechaa= fn.fechaactual();
        int  dia1=fn.edia(fechaa);
        int   mes1=fn.emes(fechaa)+1;
         String vidus=claveusuario.getText();
         apropa.lid_usuario.setText( vidus);
        String mes=null;
        String dia=null;
        if(mes1>=1 && mes1<10){
            mes="0"+ mes1+"/";
        }
        if(mes1>9){
           dia=mes1+"/";
        }
        if(dia1>=1 && dia1<10){
            dia="0"+ dia1+"/";
        }
        if(dia1>9){
           dia=dia1+"/";
        }
         int año1=fn.eaño(fechaa);
        apropa.txtfechainicio.setText(fechaa);
          apropa.txtfechafi.setText(dia+mes+año1);
        apropa.nombrevendededor=lnombre_us.getText();
        vocionesapartado.setVisible(false);
          apropa.setVisible(true);
        }
        else{
            apropa.setVisible(false);
        }
        
      //  Cambio_apartado2.nombreusa=lnombre_us.getText();
         } catch(Exception e){
           System.out.println(e);
       }
        
    }//GEN-LAST:event_btningresar5ActionPerformed

    private void btnprenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprenda1ActionPerformed
       try{
        boolean verda=true;
        if( vocionesapartado.isVisible()==false){
            vocionesapartado.setVisible(true);
        }
        else{
            vocionesapartado.setVisible(false);
        }
 } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnprenda1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    try{
        Salir sal= new Salir();
       sal.setVisible(true);
       this.setVisible(false);
        } catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_formWindowClosed
    
    Apartado_pagos apagos= new Apartado_pagos();
    public void ppantalla(){
   
}
  public void iniciopordefault(){
       jPanel6.setVisible(false);
       jPanel7.setVisible(false);
       jPanel8.setVisible(false);
       jPanel9.setVisible(false);
       jPanel10.setVisible(false);
  }  
    
    
   public void   mostraradmin(){
         btnprenda.setVisible(true);
        btnreporteventas.setVisible(true);
        vropaopciones.setVisible(false);
        vocionesapartado.setVisible(false);
        btnprenda1.setVisible(true);
        btningresar7.setVisible(true);
        btnregistrarproducto.setVisible(true);
        btninventario.setVisible(true);
        btnusuarios.setVisible(true);
   }
   
     public void   mostrarempledo(){
         btnprenda.setVisible(true);
        btnreporteventas.setVisible(true);
        vropaopciones.setVisible(false);
        vocionesapartado.setVisible(false);
        btnprenda1.setVisible(true);
        btningresar7.setVisible(true);
        btnregistrarproducto.setVisible(false);
        btninventario.setVisible(false);
        btnusuarios.setVisible(false);
        
   }
    
    
    public void agregaradmin(){
        btnusuarios.setVisible(true);
      //  us.cbtipo.setSelectedIndex(1);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btningresar1;
    public javax.swing.JButton btningresar5;
    public javax.swing.JButton btningresar6;
    public javax.swing.JButton btningresar7;
    public javax.swing.JButton btninventario;
    public javax.swing.JButton btnprenda;
    public javax.swing.JButton btnprenda1;
    public javax.swing.JButton btnregistrarproducto;
    public javax.swing.JButton btnreporteventas;
    public javax.swing.JButton btnusuarios;
    public javax.swing.JLabel claveusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lnombre_us;
    public javax.swing.JLabel lnombre_us2;
    public javax.swing.JLabel ltipousuario;
    private javax.swing.JDesktopPane pantalla;
    public javax.swing.JPanel vocionesapartado;
    public javax.swing.JPanel vropaopciones;
    // End of variables declaration//GEN-END:variables
}
