/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import clasesmetodos.Ropa_metodos;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import clases.Venta;
import clasesmetodos.Venta_metodos;
import metodosvarios.Fecha;
import clases.Agregar;
import clasesmetodos.Agregar_metodos;
import clasesmetodos.Apartado_metodos;
import javax.swing.JOptionPane;
/**
 *
 * @author 
 */
public class Inventario extends javax.swing.JInternalFrame {
Ropa_metodos rp= new Ropa_metodos();
Venta ven=new Venta();
Venta_metodos vendao= new Venta_metodos();
Ropa_metodos rm= new Ropa_metodos();
Agregar ag=new  Agregar();
Agregar_metodos agdao= new Agregar_metodos();
Fecha fn= new Fecha();
Apartado_metodos adao= new Apartado_metodos();
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        vdatosproductos.setVisible(false);
        vagregar.setVisible(false);
       btnagregar.setVisible(false);
       btncancelar.setVisible(false);
       Agregar1.setVisible(false);
    }
    public boolean mi(String tii){
        boolean mires=true;
          int cantaex=rp.ropaTDA(tii).getCantidad_existente();
          String tipopro=rp.ropaTDA(tii).getTipo_producto();
    txtcantiidadi.setText(Integer.toString(cantaex));
    
    txtdescripcioni.setText("TIPO DE PRENDA:  "+ tipopro+"  MARCA:  "+rp.ropaTDA(tii).getMarca()+"  TALLA:  "+rp.ropaTDA(tii).getTalla() +"  DETALLES:  "+rp.ropaTDA(tii).getDescripcion()+"  PRECIO:  $ "+rp.ropaTDA(tii).getPrecio());
       if(tipopro==null){
           mires=false;
       }
       
       return  mires;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigoi = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        vagregar = new javax.swing.JPanel();
        txtagregari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Agregar1 = new javax.swing.JButton();
        vdatosproductos = new javax.swing.JPanel();
        txtdescripcioni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcantiidadi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_inventariototal = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtfechaventas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inventarioventas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtfecha_apartadoi = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_apartadoi = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_agregar = new javax.swing.JTable();
        txtfechaagregar = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CODIGO PRODUCTO");

        txtcodigoi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtcodigoi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoiActionPerformed(evt);
            }
        });
        txtcodigoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoiKeyReleased(evt);
            }
        });

        btnagregar.setBackground(new java.awt.Color(0, 153, 0));
        btnagregar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(51, 0, 0));
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodigoi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnagregar))
        );

        vagregar.setBackground(new java.awt.Color(255, 255, 255));

        txtagregari.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtagregari.setForeground(new java.awt.Color(0, 0, 255));
        txtagregari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtagregari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtagregariKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("CANTIDAD AGREGAR");

        Agregar1.setBackground(new java.awt.Color(0, 102, 0));
        Agregar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        Agregar1.setText("ACEPTAR");
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vagregarLayout = new javax.swing.GroupLayout(vagregar);
        vagregar.setLayout(vagregarLayout);
        vagregarLayout.setHorizontalGroup(
            vagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vagregarLayout.createSequentialGroup()
                .addGroup(vagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vagregarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtagregari, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vagregarLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vagregarLayout.setVerticalGroup(
            vagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vagregarLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtagregari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar1))
                .addGap(49, 49, 49))
        );

        vdatosproductos.setBackground(new java.awt.Color(255, 255, 255));

        txtdescripcioni.setEditable(false);
        txtdescripcioni.setBackground(new java.awt.Color(255, 255, 255));
        txtdescripcioni.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtdescripcioni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdescripcioni.setBorder(null);

        jLabel8.setBackground(new java.awt.Color(0, 0, 153));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" UNIDADES EXISTENTES");

        txtcantiidadi.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtcantiidadi.setForeground(new java.awt.Color(51, 255, 51));
        txtcantiidadi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcantiidadi.setText("5");

        javax.swing.GroupLayout vdatosproductosLayout = new javax.swing.GroupLayout(vdatosproductos);
        vdatosproductos.setLayout(vdatosproductosLayout);
        vdatosproductosLayout.setHorizontalGroup(
            vdatosproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vdatosproductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtdescripcioni, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vdatosproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcantiidadi, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vdatosproductosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vdatosproductosLayout.setVerticalGroup(
            vdatosproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vdatosproductosLayout.createSequentialGroup()
                .addGroup(vdatosproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vdatosproductosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcantiidadi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vdatosproductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdescripcioni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabla_inventariototal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_inventariototal);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TOTAL DE INVENTARIO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtfechaventas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtfechaventas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechaventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaventasActionPerformed(evt);
            }
        });

        tabla_inventarioventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_inventarioventas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechaventas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtfechaventas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("VENTAS POR FECHA", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtfecha_apartadoi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtfecha_apartadoi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha_apartadoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfecha_apartadoiActionPerformed(evt);
            }
        });

        tabla_apartadoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabla_apartadoi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha_apartadoi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtfecha_apartadoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("APARTADO POR FECHA", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tabla_agregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_agregar);

        txtfechaagregar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtfechaagregar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechaagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtfechaagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 164, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txtfechaagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ALTA DE PRODUCTO POR FECHA", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(vdatosproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(vdatosproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
      vagregar.setVisible(true);
      txtcodigoi.setEditable(false);
      btnagregar.setVisible(false);
      btncancelar.setVisible(true);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
     Agregar1.setVisible(false);
        guardar_aumentainventario();
    vaciaventanaagregar();
    txtcodigoi.setEditable(true);
    txtcodigoi.setText(null);
    btnagregar.setVisible(false);
    vdatosproductos.setVisible(false);
   
    mostrarropa(tabla_inventariototal);
    reporteagregarpor(tabla_agregar,fn.fechaactual());
     
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtcodigoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoiActionPerformed
       
        if(mi(txtcodigoi.getText())==true){
          vdatosproductos.setVisible(true);
           btnagregar.setVisible(true);
        
        }
    
        else{
             txtcodigoi.setText(null);
              vdatosproductos.setVisible(false);
              vaciaventanaagregar();
                 JOptionPane.showMessageDialog(null, "EL CODIGO DEL PRODUCTO NO HA SIDO REGISTRADO");
        }
    }//GEN-LAST:event_txtcodigoiActionPerformed

    private void txtcodigoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoiKeyReleased

    }//GEN-LAST:event_txtcodigoiKeyReleased

    private void txtfechaventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaventasActionPerformed
        reporteventaspor(tabla_inventarioventas,txtfechaventas.getText());
    }//GEN-LAST:event_txtfechaventasActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
         mostrarropa(tabla_inventariototal);
         txtfechaventas.setText(fn.fechaactual());
         txtfechaagregar.setText(fn.fechaactual());
         txtfecha_apartadoi.setText(fn.fechaactual());
         reporteventaspor(tabla_inventarioventas,txtfechaventas.getText());
         reporteagregarpor(tabla_agregar,txtfechaagregar.getText());
          reporteapartadopor(tabla_apartadoi,txtfecha_apartadoi.getText());
    }//GEN-LAST:event_formInternalFrameActivated

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtcodigoi.setEditable(true);
         vaciaventanaagregar();
          txtcodigoi.setText(null);
    btnagregar.setVisible(false);
    vdatosproductos.setVisible(false);
    Agregar1.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtfechaagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaagregarActionPerformed
      reporteagregarpor(tabla_agregar,txtfechaagregar.getText());
    }//GEN-LAST:event_txtfechaagregarActionPerformed

    private void txtagregariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtagregariKeyReleased
       if(txtagregari.getText().isEmpty()==true){
           Agregar1.setVisible(false); 
       }
       else{
           int trte= Integer.parseInt(txtagregari.getText());
           if(trte>=1){
            Agregar1.setVisible(true);
           }
           else{
                 Agregar1.setVisible(false); 
           }
       }
       
       
    }//GEN-LAST:event_txtagregariKeyReleased

    private void txtfecha_apartadoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfecha_apartadoiActionPerformed
        reporteapartadopor(tabla_apartadoi,txtfecha_apartadoi.getText());
    }//GEN-LAST:event_txtfecha_apartadoiActionPerformed
 
    public void guardar_aumentainventario(){
        ag.setId_ropa(txtcodigoi.getText());
        ag.setId_usuario(1);
        ag.setFecha(fn.fechaactual());
        ag.setHora(fn.hora_completa());
        ag.setCantidad(Integer.parseInt(txtagregari.getText()));
        agdao.guardar_inventario(ag);
    }
    
    
    
    public void vaciaventanaagregar(){
        btnagregar.setVisible(false);
        vagregar.setVisible(false);
        txtagregari.setText(null);
        btncancelar.setVisible(false);
    }
    ///////
       public void reporteagregarpor(JTable tablaD,String t) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("ID");
       modeloTabla.addColumn("PRODUCTO");
       modeloTabla.addColumn("HORA");
       modeloTabla.addColumn("CANTIDAD");
  
      
    

        Object[] columna = new Object[4];
        int numReg=agdao.listaragregarporfecha(t).size();

        for (int i = 0; i < numReg; i++) {
       
           String aid_rpa=agdao.listaragregarporfecha(t).get(i).getId_ropa();
           
          
          columna[0] = agdao.listaragregarporfecha(t).get(i).getId_ropa();
          columna[1] = describropa(aid_rpa);
          columna[2] = agdao.listaragregarporfecha(t).get(i).getHora();
          columna[3] = agdao.listaragregarporfecha(t).get(i).getCantidad();
      
            modeloTabla.addRow(columna);
        }
        
     
    } 
    
    /////////
        public void reporteapartadopor(JTable tablaD,String t) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("NO");
       modeloTabla.addColumn("PRODUCTO");
       modeloTabla.addColumn("REFERENCIA DE APARTADO");
       modeloTabla.addColumn("CANTIDAD");
  
      
    

        Object[] columna = new Object[4];
        int numReg=adao.apartadodeporfecha(t).size();

        for (int i = 0; i < numReg; i++) {
           String id_vnta=adao.apartadodeporfecha(t).get(i).getId_apartado();
           String id_rpa=adao.apartadodeporfecha(t).get(i).getId_ropa();
           
          
          columna[0] = i+1;
          columna[1] = describropa(id_rpa);
          columna[2] = id_vnta;
          columna[3] = adao.apartadodeporfecha(t).get(i).getCantidad_apartado();
      
            modeloTabla.addRow(columna);
        }}
        
     
    /////////////////7
    public void reporteventaspor(JTable tablaD,String t) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("NO");
       modeloTabla.addColumn("PRODUCTO");
       modeloTabla.addColumn("REFERENCIA DE VENTA");
       modeloTabla.addColumn("CANTIDAD");
  
      
    

        Object[] columna = new Object[4];
        int numReg=vendao.ventasDetalleventaporfecha(t).size();

        for (int i = 0; i < numReg; i++) {
           String id_vnta=vendao.ventasDetalleventaporfecha(t).get(i).getId_venta();
           String id_rpa=vendao.ventasDetalleventaporfecha(t).get(i).getId_ropa();
           
          
          columna[0] = i+1;
          columna[1] = describropa(id_rpa);
          columna[2] = id_vnta;
          columna[3] = vendao.ventasDetalleventaporfecha(t).get(i).getCantidad();
      
            modeloTabla.addRow(columna);
        }
        
     
    } 
    
    /////////7
public String describropa(String id_r){
     String descripcion=null;

   descripcion=rm.ropaTDA(id_r).getMarca()+" "+rm.ropaTDA(id_r).getTipo_producto()+" "+rm.ropaTDA(id_r).getTalla();
return  descripcion;
}
/////////
      public void mostrarropa(JTable tablaD) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("CLAVE");
       modeloTabla.addColumn("TIPO DE PRENDA");
       modeloTabla.addColumn("MARCA");
       modeloTabla.addColumn("TALLA");
       modeloTabla.addColumn("DESCRIPCIÓN");
        modeloTabla.addColumn("PRECIO");
        modeloTabla.addColumn("INVENTARIO");
      
    

        Object[] columna = new Object[7];
        int numReg=rm.ropatodo().size();

        for (int i = 0; i < numReg; i++) {
            
          columna[0] = rm.ropatodo().get(i).getClave();
          columna[1] = rm.ropatodo().get(i).getTipo_producto();
          columna[2] = rm.ropatodo().get(i).getMarca();
          columna[3] = rm.ropatodo().get(i).getTalla();
          columna[4] = rm.ropatodo().get(i).getDescripcion();
          columna[5] = rm.ropatodo().get(i).getPrecio();
          columna[6] = rm.ropatodo().get(i).getCantidad_existente();
       
           
        

           
            modeloTabla.addRow(columna);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Agregar1;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_agregar;
    public javax.swing.JTable tabla_apartadoi;
    private javax.swing.JTable tabla_inventariototal;
    private javax.swing.JTable tabla_inventarioventas;
    private javax.swing.JTextField txtagregari;
    public javax.swing.JLabel txtcantiidadi;
    private javax.swing.JTextField txtcodigoi;
    public javax.swing.JTextField txtdescripcioni;
    public javax.swing.JTextField txtfecha_apartadoi;
    private javax.swing.JTextField txtfechaagregar;
    private javax.swing.JTextField txtfechaventas;
    private javax.swing.JPanel vagregar;
    public javax.swing.JPanel vdatosproductos;
    // End of variables declaration//GEN-END:variables
}
