/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import clasesmetodos.Usuario_metodos;
import clasesmetodos.Venta_metodos;
import metodosvarios.Fecha;
/**
 *
 * @author 
 */
public class Reporte_ventas extends javax.swing.JInternalFrame {
    
Venta_metodos vm= new Venta_metodos();
Usuario_metodos usm= new Usuario_metodos();
Fecha fn= new Fecha();

    /**
     * Creates new form Reporte_ventas
     */
    public Reporte_ventas() {
        initComponents();
      
        
        
        
    }
   public void reporteventaspor(JTable tablaD,String t) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaD.setModel(modeloTabla);
       
     modeloTabla.addColumn("NO");
       modeloTabla.addColumn("HORA");
       modeloTabla.addColumn("TOTAL DE VENTA");
       modeloTabla.addColumn("RESPONSABLE DE LA VENTA");
  
      
    

        Object[] columna = new Object[4];
        int numReg=vm.ventastotal(t).size();

        for (int i = 0; i < numReg; i++) {
           int id_us= vm.ventastotal(t).get(i).getId_usuario();
          
          columna[0] = i+1;
          columna[1] = vm.ventastotal(t).get(i).getHora();
          columna[2] =vm.ventastotal(t).get(i).getTotal_venta();
          columna[3] =usm.usTDAporid(id_us).getNombre_completo();
      
            modeloTabla.addRow(columna);
        }
     
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablareporteventas = new javax.swing.JTable();
        txtfechaconsultaventa = new javax.swing.JTextField();
        ltotalventasrv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablareporteventas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tablareporteventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablareporteventas);

        txtfechaconsultaventa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtfechaconsultaventa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechaconsultaventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaconsultaventaActionPerformed(evt);
            }
        });
        txtfechaconsultaventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfechaconsultaventaKeyReleased(evt);
            }
        });

        ltotalventasrv.setFont(new java.awt.Font("Calisto MT", 1, 48)); // NOI18N
        ltotalventasrv.setForeground(new java.awt.Color(51, 51, 255));
        ltotalventasrv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotalventasrv.setText("$ 0");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("TOTAL DE DINERO EN LAS VENTAS REALIZADAS DURANTE EL DIA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtfechaconsultaventa, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ltotalventasrv, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtfechaconsultaventa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ltotalventasrv)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfechaconsultaventaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaconsultaventaKeyReleased
        
    }//GEN-LAST:event_txtfechaconsultaventaKeyReleased

    private void txtfechaconsultaventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaconsultaventaActionPerformed
       String fecharv=null;
       fecharv=txtfechaconsultaventa.getText();
        reporteventaspor(tablareporteventas,fecharv);
     int tamrven=   tablareporteventas.getRowCount();
     if( tamrven>0){
      sumaventa();
     }
     else{
          ltotalventasrv.setText(null);
     }
       
      
    }//GEN-LAST:event_txtfechaconsultaventaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        txtfechaconsultaventa.setText(fn.fechaactual());
        reporteventaspor(tablareporteventas,fn.fechaactual());
        int tamrven=   tablareporteventas.getRowCount();
     if( tamrven>0){
      sumaventa();
     }
     else{
          ltotalventasrv.setText(null);
     }
       
    }//GEN-LAST:event_formInternalFrameOpened




   public void sumaventa(){
       int tamañovector=tablareporteventas.getRowCount();
          if(tamañovector>0){
              double tf=0;
              int lart=0;
              for (int i =0; i < tamañovector; i++) {
           
                  double tprec=Double.parseDouble(tablareporteventas.getModel().getValueAt(i,2).toString());
                  
                  
                tf=tf+tprec;
               ltotalventasrv.setText("$ "+Double.toString(tf));
}}
  }  
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ltotalventasrv;
    private javax.swing.JTable tablareporteventas;
    private javax.swing.JTextField txtfechaconsultaventa;
    // End of variables declaration//GEN-END:variables
}
