/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clasesmetodos.Ropa_metodos;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import metodosvarios.Varios;
import metodosvarios.Fecha;
import clases.Venta;
import clasesmetodos.Venta_metodos;
import static interfaces.Cambio.valorventa;
import java.awt.Color;
import javax.swing.event.TableModelEvent;


/**
 *
 * @author 
 */
public class Ventas_ropa extends javax.swing.JInternalFrame {
DefaultTableModel modeloTabla;
DefaultListModel lista= new DefaultListModel();
Recibo recibo = new Recibo();
Recibos recibos= new Recibos();
Fecha fn= new Fecha();
Venta vn=new Venta();
Venta_metodos vm= new Venta_metodos();

Cambio cambio=new Cambio();

Varios va= new Varios();


Ropa_metodos rm= new Ropa_metodos();
    /**
     * Creates new form Ventas_ropa
     */
    public Ventas_ropa() {
        initComponents();
        
         this.setClosable(true);
        this.setMaximizable(true);
        String encabezado[]={"CLAVE","CANTIDAD","DESCRIPCION","PRECIO","TOTAL"}; String datos[][]={};
        modeloTabla=new DefaultTableModel(datos,encabezado); 
       
        
        vagrega.setVisible(false);
        
        tabla_ventas.setModel(modeloTabla);
        scrolltventas.setBackground(java.awt.Color.red);
        txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        tabla_ventas.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        tabla_ventas.getTableHeader().setOpaque(false);
        tabla_ventas.getTableHeader().setBackground(java.awt.Color.WHITE);
        tabla_ventas.getTableHeader().setForeground(java.awt.Color.BLUE);
        tabla_ventas.setRowHeight(25);
      vcambio.setVisible(false);
      lista= new DefaultListModel();
      listaventas.setModel(lista);
      lid_venta.setVisible(false);
      lid_usuario.setVisible(false);
      lborrarrow.setVisible(false);
      lv_idus.setVisible(false);
        scrolltventas.getViewport().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        larticulos = new javax.swing.JLabel();
        vcambio = new javax.swing.JPanel();
        lborrarrow = new javax.swing.JLabel();
        leliminarow = new javax.swing.JLabel();
        lid_usuario = new javax.swing.JLabel();
        lv_idus = new javax.swing.JLabel();
        lid_venta = new javax.swing.JLabel();
        lcodicolor = new javax.swing.JLabel();
        lcam = new javax.swing.JLabel();
        ldinerorecibido = new javax.swing.JLabel();
        ventanatabla = new javax.swing.JPanel();
        scrolltventas = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        labelcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        vagrega = new javax.swing.JPanel();
        scroll_lista = new javax.swing.JScrollPane();
        listaventas = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lpago = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CANTIDAD DE ARTICULOS");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        larticulos.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        larticulos.setForeground(new java.awt.Color(0, 255, 0));
        larticulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        larticulos.setText("0");
        larticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                larticulosMouseClicked(evt);
            }
        });

        vcambio.setBackground(new java.awt.Color(255, 255, 255));

        lborrarrow.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lborrarrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lborrarrow.setText("0");

        leliminarow.setText("-1");

        lid_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lid_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lid_usuario.setText("1");

        lv_idus.setText("1555555555555555555");

        lid_venta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lid_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lid_venta.setText("123");

        lcodicolor.setText("0");

        javax.swing.GroupLayout vcambioLayout = new javax.swing.GroupLayout(vcambio);
        vcambio.setLayout(vcambioLayout);
        vcambioLayout.setHorizontalGroup(
            vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vcambioLayout.createSequentialGroup()
                .addGroup(vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vcambioLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(leliminarow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lborrarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodicolor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vcambioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lv_idus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vcambioLayout.createSequentialGroup()
                                .addComponent(lid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        vcambioLayout.setVerticalGroup(
            vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vcambioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leliminarow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lborrarrow)
                        .addComponent(lcodicolor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(vcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lv_idus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ventanatabla.setBackground(new java.awt.Color(255, 255, 255));

        scrolltventas.setBackground(new java.awt.Color(255, 255, 255));
        scrolltventas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        scrolltventas.setOpaque(false);

        tabla_ventas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla_ventas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_ventas.setFocusable(false);
        tabla_ventas.setGridColor(new java.awt.Color(51, 255, 51));
        tabla_ventas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla_ventas.setOpaque(false);
        tabla_ventas.setRowHeight(100);
        tabla_ventas.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabla_ventas.setShowVerticalLines(false);
        tabla_ventas.getTableHeader().setReorderingAllowed(false);
        scrolltventas.setViewportView(tabla_ventas);

        javax.swing.GroupLayout ventanatablaLayout = new javax.swing.GroupLayout(ventanatabla);
        ventanatabla.setLayout(ventanatablaLayout);
        ventanatablaLayout.setHorizontalGroup(
            ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanatablaLayout.createSequentialGroup()
                .addComponent(scrolltventas, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventanatablaLayout.setVerticalGroup(
            ventanatablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanatablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolltventas, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        labelcodigo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcodigo.setText("CODIGO DE ROPA");
        labelcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcodigoMouseClicked(evt);
            }
        });

        txtcodigo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));
        txtcodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcodigoCaretUpdate(evt);
            }
        });
        txtcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcodigoMouseClicked(evt);
            }
        });
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });

        vagrega.setBackground(new java.awt.Color(219, 244, 197));

        listaventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listaventas.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        listaventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaventasMouseClicked(evt);
            }
        });
        scroll_lista.setViewportView(listaventas);

        javax.swing.GroupLayout vagregaLayout = new javax.swing.GroupLayout(vagrega);
        vagrega.setLayout(vagregaLayout);
        vagregaLayout.setHorizontalGroup(
            vagregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vagregaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vagregaLayout.setVerticalGroup(
            vagregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vagregaLayout.createSequentialGroup()
                .addComponent(scroll_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL DE COMPRA");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        lpago.setFont(new java.awt.Font("Arial Narrow", 1, 40)); // NOI18N
        lpago.setForeground(new java.awt.Color(0, 204, 0));
        lpago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpago.setText("0");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vcambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcam, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventanatabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vagrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 303, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(lpago, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(larticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1317, Short.MAX_VALUE)
                    .addComponent(ldinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 751, Short.MAX_VALUE)
                        .addComponent(lcam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpago, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vagrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventanatabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(larticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(634, Short.MAX_VALUE)
                    .addComponent(ldinerorecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int tamañolabel=modeloTabla.getRowCount();

    }//GEN-LAST:event_jLabel4MouseClicked

    private void larticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_larticulosMouseClicked
        lista.clear();
    }//GEN-LAST:event_larticulosMouseClicked

    private void labelcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcodigoMouseClicked
        int lcl= Integer.parseInt(lcodicolor.getText());

        if(lcl==0){
            lcodicolor.setText("1");
            txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        }
        else{
            lcodicolor.setText("0");
            txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        }
    }//GEN-LAST:event_labelcodigoMouseClicked

    private void txtcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodigoMouseClicked

    }//GEN-LAST:event_txtcodigoMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

        ventasaction();

    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyReleased
      
        String codiropa=txtcodigo.getText();
        char c = evt.getKeyChar();
        int tamt_bla= modeloTabla.getRowCount();
        int clavetecla=evt.getExtendedKeyCode();
        String codiropabd=rm.ropaTDA(codiropa).getClave();

        ///////

        System.out.println("tecla = "+clavetecla);
        va.borracaja(txtcodigo, evt);

        if(txtcodigo.getText().isEmpty()){
            System.out.println("no hay en dinero recibido");
        }
        if(clavetecla==16){

            if( vagrega.isVisible()==false){
                vagrega.setVisible(true);

            }
            else{
                vagrega.setVisible(false);
            }

        }
        if( vagrega.isVisible()==true){
            mostrardatos(codiropa);

        }
        else{
            vagrega.setVisible(false);
        }

        if(tamt_bla>=1){
            
            if(clavetecla==17){
                String vid_us=lv_idus.getText();
                cambio.setVisible(true);
                extraerdatostabla();
                int tana= modeloTabla.getRowCount();
               cambio.tamañodedatos.setText(Integer.toString(tana));
               cambio.lid_usuarioc.setText(vid_us);
               cambio. ltotale.setText(lpago.getText());
              
                
                }
          
                /*
                String total_pago= lpago.getText();
                guardarventa();
                cambio.setVisible(true);
                cambio.ltotale.setText(total_pago);
                 limpiartabla(tamt_bla);
                 int id_i=Integer.parseInt (lid_venta.getText());
                 String id_iv = Integer.toString((id_i + 1));
                 
                 lid_venta.setText(id_iv);
                

                //recibo.imprimirrecibo();
               */

            }

    }//GEN-LAST:event_txtcodigoKeyReleased

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped

    }//GEN-LAST:event_txtcodigoKeyTyped

    private void listaventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaventasMouseClicked

    }//GEN-LAST:event_listaventasMouseClicked

    private void txtcodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcodigoCaretUpdate
     
    }//GEN-LAST:event_txtcodigoCaretUpdate

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
     
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
     
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
     
    }//GEN-LAST:event_formInternalFrameIconified

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
       
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
  
      
    }//GEN-LAST:event_jLabel3MouseClicked
public void limpiartabla(){
    int modlta= modeloTabla.getRowCount()-1;
    for (int o = modlta; o>-1; o--) {
        modeloTabla.removeRow(o);
    }
  } 
    
   
   
   
    //////////////7777
      
    
    
   public void extraerdatostabla(){
        // DefaultTableModel modeloTabla = new DefaultTableModel();
        //tablaD.setModel(modeloTabla);
       int textraer = modeloTabla.getRowCount();
       
  
      
        
          for (int qr =0; qr< textraer; qr++) {
              System.out.println("Q= "+ qr);
            String tclave=tabla_ventas.getModel().getValueAt(qr, 0).toString();
            int tcantidad = Integer.parseInt(tabla_ventas.getModel().getValueAt(qr, 1).toString());
            String tdescripcion=tabla_ventas.getModel().getValueAt(qr, 2).toString();
            double tprecio = Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 3).toString());
            double totale= Double.parseDouble(tabla_ventas.getModel().getValueAt(qr, 4).toString());
            cambio.tablacambio.setValueAt(tclave, qr, 0);
            cambio.tablacambio.setValueAt(tcantidad, qr, 1);
            cambio.tablacambio.setValueAt(tdescripcion, qr, 2);
            cambio.tablacambio.setValueAt(tprecio, qr, 3);
            cambio.tablacambio.setValueAt(totale, qr, 4);
            
         
        
    }
          
   }
      
      
            
      
      
      
      
      
      
      
    /////////777
    
    
    
   public void ventasaction(){
       int tam = tabla_ventas.getRowCount();
      
         String tipoa = txtcodigo.getText();
         String clave=rm.ropaTDA(tipoa).getClave();
        double precio = rm.ropaTDA(tipoa).getPrecio();
      String descripcion=rm.ropaTDA(tipoa).getTipo_producto()+" "+rm.ropaTDA(tipoa).getMarca()+" "+rm.ropaTDA(tipoa).getTalla();
        
         int tcolor=Integer.parseInt(lcodicolor.getText());
        if(tipoa.equals(clave)){
           ventas(tam,precio,tipoa,tcolor,descripcion);  
        }
    
        txtcodigo.setText(null);
   } 
    
    
    public void m1(){
       int tamañovector=modeloTabla.getDataVector().size();
          if(tamañovector>0){
              double tf=0;
              int lart=0;
              for (int i =0; i < tamañovector; i++) {
           
                  double tprec=Double.parseDouble(tabla_ventas.getModel().getValueAt(i,4).toString());
                  int lrt=Integer.parseInt(tabla_ventas.getModel().getValueAt(i,1).toString());
                  
                tf=tf+tprec;
                lart=lart+lrt;
               
                  lpago.setText(Double.toString(tf));
                  larticulos.setText(Integer.toString(lart));
}}
  }  
   
  
      
    public void ventas(int t,double precio,String tipoa,int tcolor,String descripcion){
       int opcion=0;

        int cantidad = 1;
        
        double total = precio * cantidad;
        
        Object registro[] = new Object[]{tipoa,cantidad,descripcion, precio, total};
        
         if(t==0){
           if(tcolor==0){
              opcion=1;
           }  
           if(tcolor==1){
              opcion=0;
           }  
        }
         
        if (t >= 1) {
       if(tcolor==0){
              opcion=2;
               System.out.println("condicio >1 para el case 2 = "+tcolor);
           }  
           if(tcolor==1){
              opcion=3;
               System.out.println("condicio >1 para el case 3 = "+tcolor);
           }  
        }
         
        switch(opcion){
            case 0:
                System.out.println("nada");  
            break;
                  
            case 1: 
            modeloTabla.addRow(registro);
            lpago.setText(Double.toString(precio));
            larticulos.setText(Integer.toString(1));
             break;  
             
             
            case 2:
             
               if (vender(t, tipoa,1) == false) {
                modeloTabla.addRow(registro);
             
            }
         rellenatabla(t);
              
             break;
            case 3:
        
            int cvtam= cance_venta(t,tipoa,1);
            rellenatabla(t);
           int rowdelete=Integer.parseInt( leliminarow.getText());
            if(rowdelete>-1){
                System.out.println("HOLA"); 
                modeloTabla.removeRow(rowdelete);
                leliminarow.setText(Integer.toString(-1));
            }
            
                break;
            default:
                System.out.println("nada");
                break;
        }
    }
    
    public void rellenatabla(int t){
          for (int m = 0; m < t; m++) {
                
              int cant = Integer.parseInt(tabla_ventas.getModel().getValueAt(m, 1).toString());
            double prec = Double.parseDouble(tabla_ventas.getModel().getValueAt(m, 3).toString());
            double totale=cant*prec;
          
            tabla_ventas.setValueAt(totale,m, 4);
       
  //cancelarventa(t);
            m1();
        }
    }

    
    public boolean vender(int tam,String tipoa,int tcan ){
       boolean tt=false;
       int i=0;
             while (i<tam) { 
                   String cc = tabla_ventas.getModel().getValueAt(i,0).toString();
               if(cc.equals(tipoa)){
                    int can= Integer.parseInt(tabla_ventas.getModel().getValueAt(i,1).toString());
                       int ttcant = tcan;
                    
                        tabla_ventas.setValueAt((can + ttcant),i,1);
                        tt=true;
               }
               i++;
             }
                   return tt;
             }
    
    public int cance_venta(int tam,String tipoa,int tcan){
        int cv= -1;
       int ñ=0;
        
             while (ñ<tam) { 
       String cc = tabla_ventas.getModel().getValueAt(ñ,0).toString();
                
               if(cc.equals(tipoa)){
            
                    int canttt= Integer.parseInt(tabla_ventas.getModel().getValueAt(ñ,1).toString());
                      int ttcant = tcan;
                     int cantireal= (canttt - ttcant);
                    if(cantireal==0){
                        leliminarow.setText(Integer.toString(ñ));
                       cv=0;
                         
                    }
                    
                     tabla_ventas.setValueAt(cantireal,ñ,1);}
               ñ++;}
             return cv;}
    
     public void mostrardatos(String t) {
          lista= new DefaultListModel();
          listaventas.setModel(lista);
        lista.insertElementAt("CLAVE"+" TIPO"+" MARCA"+"DESCRIPCION"+"TALLA"+"PRECIO", 0);
   
        int numReg = rm.Ropatotal(t).size();
      

        for (int i = 0; i < numReg; i++) {
            
          String cla_r =  rm.Ropatotal(t).get(i).getClave();
          String tipo_r =  rm.Ropatotal(t).get(i).getTipo_producto();
          String marca_r =  rm.Ropatotal(t).get(i).getMarca();
          String desc_r =  rm.Ropatotal(t).get(i).getDescripcion();
          String talla_r =  rm.Ropatotal(t).get(i).getTalla();
          double precio_r =  rm.Ropatotal(t).get(i).getPrecio();
          
          lista.addElement(cla_r+" "+ tipo_r+" "+marca_r+" "+desc_r+" "+talla_r+" "+precio_r);
        }
    }

     public void guardarventa(){
         vn.setId_venta(lid_venta.getText());
         vn.setId_usuario(Integer.parseInt(lid_usuario.getText()));
         vn.setFecha(fn.fechaactual());
         vn.setHora(fn.hora_completa());
         vn.setTotal_venta(lpago.getText());
         vm.guardar_venta(vn);
     }
     
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelcodigo;
    public javax.swing.JLabel larticulos;
    public javax.swing.JLabel lborrarrow;
    private javax.swing.JLabel lcam;
    private javax.swing.JLabel lcodicolor;
    private javax.swing.JLabel ldinerorecibido;
    private javax.swing.JLabel leliminarow;
    private javax.swing.JLabel lid_usuario;
    private javax.swing.JLabel lid_venta;
    private javax.swing.JList<String> listaventas;
    public javax.swing.JLabel lpago;
    public javax.swing.JLabel lv_idus;
    private javax.swing.JScrollPane scroll_lista;
    private javax.swing.JScrollPane scrolltventas;
    public javax.swing.JTable tabla_ventas;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JPanel vagrega;
    public javax.swing.JPanel vcambio;
    private javax.swing.JPanel ventanatabla;
    // End of variables declaration//GEN-END:variables
}
